apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-prom-stack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "60.x"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 5m
  values:
    prometheus:
      prometheusSpec:
        retention: 15d
        serviceMonitorSelectorNilUsesHelmValues: false
    grafana:
      defaultDashboardsEnabled: true
