apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: batch/v1
kind: Job
metadata:
  name: install-argocd
  namespace: argocd
spec:
  template:
    spec:
      containers:
      - name: argocd-install
        image: bitnami/kubectl:latest
        command:
          - /bin/sh
          - -c
          - |
            kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
        restartPolicy: OnFailure